version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  app2:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "5001:5001"
